class Columns:
       display = ['postcode', 'jaar', 'fiets_naar_werk_school', 'naam', 'shape_area', 'shape_length']
       enq = ['bibliotheek_bezocht', 'boek_gelezen', 'museum_bezocht', 'park_bezocht',
       'restaurant_of_cafe_bezocht', 'televisie_gekeken',
       'voorstelling_bezocht', 'sport_beoefend']
       opp = ['opp_sportterreinen', 'opp_gebruiksgroen_en_pleinen', 'opp_speelterreinen']
       plaatsen = ['plaatsen_buurtparkings','plaatsen_fietsenstallingen','plaatsen_velo_stations']
       total_columns_inputs = ['werkenden',
              'belastingplichtigen',
              'gemiddeld_netto_belastbaar_inkomen_per_persoon',
              'opbrengst_aanvullende_personenbelasting_per_belast',
              'dichtheid',
              'bibliotheek_bezocht',
              'boek_gelezen',
              'museum_bezocht',
              'park_bezocht',
              'restaurant_of_cafe_bezocht',
              'televisie_gekeken',
              'voorstelling_bezocht',
              'sport_beoefend',
              'regelmatig_de_fiets_naar_werk_school',
              'theorestisch_geschoolden',
              'al_basis_binnen_a',
              'al_so_binnen_a',
              'al_a_stroom',
              'al_so_geen_vertraging',
              'plaatsen_buurtparkings',
              'plaatsen_fietsenstallingen',
              'plaatsen_velo_stations',
              'opp_sportterreinen',
              'opp_gebruiksgroen_en_pleinen',
              'opp_speelterreinen','postcode']
       input_columns = ['werkenden','belastingplichtigen',
                     'gemiddeld_netto_belastbaar_inkomen_per_persoon',
                     'dichtheid', 'bibliotheek_bezocht', 'boek_gelezen',
                     'park_bezocht', 'restaurant_of_cafe_bezocht', 'televisie_gekeken',
                     'voorstelling_bezocht', 'sport_beoefend', 'theorestisch_geschoolden',
                     'al_so_geen_vertraging','plaatsen_buurtparkings',
                     'plaatsen_fietsenstallingen', 'plaatsen_velo_stations','opp_sportterreinen',
                     'opp_gebruiksgroen_en_pleinen', 'opp_speelterreinen','school_binnen_antwerpen']
       prediction_columns = ['postcode','werkenden','belastingplichtigen',
                     'gemiddeld_netto_belastbaar_inkomen_per_persoon',
                     'dichtheid', 'bibliotheek_bezocht', 'boek_gelezen',
                     'park_bezocht', 'restaurant_of_cafe_bezocht', 'televisie_gekeken',
                     'voorstelling_bezocht', 'sport_beoefend', 'theorestisch_geschoolden',
                     'al_so_geen_vertraging','school_binnen_antwerpen','plaatsen_buurtparkings',
                     'plaatsen_fietsenstallingen', 'plaatsen_velo_stations','opp_sportterreinen',
                     'opp_gebruiksgroen_en_pleinen', 'opp_speelterreinen','fiets_percentage','datum','tijd']
       min_max_columns_input = ["choose-postcode",
                            "werk-slider-0",
                            "belast-slider-0",
                            "belast-input-0",
                            "dichtheid-input-0",
                            "enq-slider-0",
                            "enq-slider-1",
                            "enq-slider-3",
                            "enq-slider-4",
                            "enq-slider-5",
                            "enq-slider-6",
                            "enq-slider-7",
                            "secundair-slider-0",
                            "vertraging-slider-0",
                            "plaatsen-input-0",
                            "plaatsen-input-1",
                            "plaatsen-input-2",
                            "opp-slider-0",
                            "opp-slider-1",
                            "opp-slider-2",
                            "school-slider-0"]
       percentage_display = ['werkenden','belastingplichtigen', 'bibliotheek_bezocht', 'boek_gelezen',
                     'park_bezocht', 'restaurant_of_cafe_bezocht', 'televisie_gekeken',
                     'voorstelling_bezocht', 'sport_beoefend', 'theorestisch_geschoolden',
                     'al_so_geen_vertraging','school_binnen_antwerpen']
       total_columns = ['postcode','werkenden',
              'belastingplichtigen',
              'gemiddeld_netto_belastbaar_inkomen_per_persoon',
              'opbrengst_aanvullende_personenbelasting_per_belast',
              'dichtheid',
              'bibliotheek_bezocht',
              'boek_gelezen',
              'museum_bezocht',
              'park_bezocht',
              'restaurant_of_cafe_bezocht',
              'televisie_gekeken',
              'voorstelling_bezocht',
              'sport_beoefend',
              'regelmatig_de_fiets_naar_werk_school',
              'theorestisch_geschoolden',
              'al_basis_binnen_a',
              'al_so_binnen_a',
              'al_a_stroom',
              'al_so_geen_vertraging',
              'plaatsen_buurtparkings',
              'plaatsen_fietsenstallingen',
              'plaatsen_velo_stations',
              'opp_sportterreinen',
              'opp_gebruiksgroen_en_pleinen',
              'opp_speelterreinen']