/*
    ___  ___  ______  |  
   / _ \/ _ \|  ____| |  agile    
  / / \ \/ \ \ |__    |  automation
 / /  /\ \  \ \ __|   |  factory   
/_/  /_/\_\  \_\      | 

Vaultspeed version: 4.1.14.0, generation date: 2020/05/12 12:48:20
DV_NAME: DEMO_ANTWERP_CITY_DATA_VAULT - Release: 2.2 predictions schema(2.2) - Comment: Predictions schema - Release date: 2020/05/12 12:44:25, 
BV release: init(1) - Comment: initial release - Release date: 2020/05/12 10:45:49, 
SRC_NAME: PRED - Release: PRED(2) - Comment: Update schema parameters - Release date: 2020/05/12 12:30:07
 */


-- SAT_TEMP_TGT

TRUNCATE TABLE "PRED_STG"."SAT_PRED_PREDICTIONS_TMP";

INSERT INTO "PRED_STG"."SAT_PRED_PREDICTIONS_TMP"(
	 "PREDICTIONS_HKEY"
	,"LOAD_DATE"
	,"LOAD_CYCLE_ID"
	,"LOAD_END_DATE"
	,"SOURCE"
	,"EQUAL"
	,"HASH_DIFF"
	,"DELETE_FLAG"
	,"DATUM"
	,"TIJD"
	,"POSTCODE"
	,"WERKENDEN"
	,"BELASTINGSPLICHTIGEN"
	,"GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON"
	,"DICHTHEID"
	,"BIBLIOTHEEK_BEZOCHT"
	,"BOEK_GELEZEN"
	,"PARK_BEZOCHT"
	,"RESTAURANT_OF_CAFE_BEZOCHT"
	,"TELEVISIE_GEKEKEN"
	,"VOORSTELLING_BEZOCHT"
	,"SPORT_BEOEFEND"
	,"THEORETISCH_GESCHOOLDEN"
	,"AL_SO_GEEN_VERTRAGING"
	,"SCHOOL_BINNEN_ANTWERPEN"
	,"PLAATSEN_BUURTPARKINGS"
	,"PLAATSEN_FIETSENSTALLINGEN"
	,"PLAATSEN_VELO_STATIONS"
	,"OPP_SPORTTERREINEN"
	,"OPP_GEBRUIKSGROEN_EN_PLEINEN"
	,"OPP_SPEELTERREINEN"
	,"FIETS_PERCENTAGE"
)
WITH "TEMP_TABLE_SET" AS 
( 
	SELECT 
		  "STG_TEMP_SRC"."PREDICTIONS_HKEY" AS "PREDICTIONS_HKEY"
		, "STG_TEMP_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS') AS "LOAD_END_DATE"
		, "STG_TEMP_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, 'STG' AS "SOURCE"
		, 1 AS "ORIGIN_ID"
		,UPPER(MD5_HEX(COALESCE(RTRIM( REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."WERKENDEN" )),'~'),'#','\\' ||
			'#')|| '#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."BELASTINGSPLICHTIGEN" )),'~'),'#','\\' || '#')
			|| '#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON" )),
			'~'),'#','\\' || '#')|| '#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."DICHTHEID" )),'~'),'#','\\' ||
			'#')|| '#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."BIBLIOTHEEK_BEZOCHT" )),'~'),'#','\\' || '#')||
			'#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."BOEK_GELEZEN" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."PARK_BEZOCHT" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."RESTAURANT_OF_CAFE_BEZOCHT" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."TELEVISIE_GEKEKEN" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."VOORSTELLING_BEZOCHT" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."SPORT_BEOEFEND" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."THEORETISCH_GESCHOOLDEN" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."AL_SO_GEEN_VERTRAGING" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."SCHOOL_BINNEN_ANTWERPEN" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."PLAATSEN_BUURTPARKINGS" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."PLAATSEN_FIETSENSTALLINGEN" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."PLAATSEN_VELO_STATIONS" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."OPP_SPORTTERREINEN" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."OPP_GEBRUIKSGROEN_EN_PLEINEN" )),'~'),'#','\\' || '#')||
			'#' ||  REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."OPP_SPEELTERREINEN" )),'~'),'#','\\' || '#')|| '#' ||
			REPLACE(COALESCE(TRIM( TO_CHAR("STG_TEMP_SRC"."FIETS_PERCENTAGE" )),'~'),'#','\\' || '#')|| '#','#' || '~'),
			'~'))) AS "HASH_DIFF"
		, CASE WHEN "STG_TEMP_SRC"."JRN_FLAG" = 'D' THEN CAST('Y'  AS VARCHAR) ELSE CAST('N'  AS VARCHAR) END AS "DELETE_FLAG"
		, "STG_TEMP_SRC"."DATUM" AS "DATUM"
		, "STG_TEMP_SRC"."TIJD" AS "TIJD"
		, "STG_TEMP_SRC"."POSTCODE" AS "POSTCODE"
		, "STG_TEMP_SRC"."WERKENDEN" AS "WERKENDEN"
		, "STG_TEMP_SRC"."BELASTINGSPLICHTIGEN" AS "BELASTINGSPLICHTIGEN"
		, "STG_TEMP_SRC"."GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON" AS "GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON"
		, "STG_TEMP_SRC"."DICHTHEID" AS "DICHTHEID"
		, "STG_TEMP_SRC"."BIBLIOTHEEK_BEZOCHT" AS "BIBLIOTHEEK_BEZOCHT"
		, "STG_TEMP_SRC"."BOEK_GELEZEN" AS "BOEK_GELEZEN"
		, "STG_TEMP_SRC"."PARK_BEZOCHT" AS "PARK_BEZOCHT"
		, "STG_TEMP_SRC"."RESTAURANT_OF_CAFE_BEZOCHT" AS "RESTAURANT_OF_CAFE_BEZOCHT"
		, "STG_TEMP_SRC"."TELEVISIE_GEKEKEN" AS "TELEVISIE_GEKEKEN"
		, "STG_TEMP_SRC"."VOORSTELLING_BEZOCHT" AS "VOORSTELLING_BEZOCHT"
		, "STG_TEMP_SRC"."SPORT_BEOEFEND" AS "SPORT_BEOEFEND"
		, "STG_TEMP_SRC"."THEORETISCH_GESCHOOLDEN" AS "THEORETISCH_GESCHOOLDEN"
		, "STG_TEMP_SRC"."AL_SO_GEEN_VERTRAGING" AS "AL_SO_GEEN_VERTRAGING"
		, "STG_TEMP_SRC"."SCHOOL_BINNEN_ANTWERPEN" AS "SCHOOL_BINNEN_ANTWERPEN"
		, "STG_TEMP_SRC"."PLAATSEN_BUURTPARKINGS" AS "PLAATSEN_BUURTPARKINGS"
		, "STG_TEMP_SRC"."PLAATSEN_FIETSENSTALLINGEN" AS "PLAATSEN_FIETSENSTALLINGEN"
		, "STG_TEMP_SRC"."PLAATSEN_VELO_STATIONS" AS "PLAATSEN_VELO_STATIONS"
		, "STG_TEMP_SRC"."OPP_SPORTTERREINEN" AS "OPP_SPORTTERREINEN"
		, "STG_TEMP_SRC"."OPP_GEBRUIKSGROEN_EN_PLEINEN" AS "OPP_GEBRUIKSGROEN_EN_PLEINEN"
		, "STG_TEMP_SRC"."OPP_SPEELTERREINEN" AS "OPP_SPEELTERREINEN"
		, "STG_TEMP_SRC"."FIETS_PERCENTAGE" AS "FIETS_PERCENTAGE"
	FROM "PRED_STG"."PREDICTIONS" "STG_TEMP_SRC"
	WHERE  "STG_TEMP_SRC"."RECORD_TYPE" = 'S'
	UNION ALL 
	SELECT 
		  "SAT_SRC"."PREDICTIONS_HKEY" AS "PREDICTIONS_HKEY"
		, "SAT_SRC"."LOAD_DATE" AS "LOAD_DATE"
		, "SAT_SRC"."LOAD_END_DATE" AS "LOAD_END_DATE"
		, "SAT_SRC"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
		, 'SAT' AS "SOURCE"
		, 0 AS "ORIGIN_ID"
		, "SAT_SRC"."HASH_DIFF" AS "HASH_DIFF"
		, "SAT_SRC"."DELETE_FLAG" AS "DELETE_FLAG"
		, "SAT_SRC"."DATUM" AS "DATUM"
		, "SAT_SRC"."TIJD" AS "TIJD"
		, "SAT_SRC"."POSTCODE" AS "POSTCODE"
		, "SAT_SRC"."WERKENDEN" AS "WERKENDEN"
		, "SAT_SRC"."BELASTINGSPLICHTIGEN" AS "BELASTINGSPLICHTIGEN"
		, "SAT_SRC"."GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON" AS "GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON"
		, "SAT_SRC"."DICHTHEID" AS "DICHTHEID"
		, "SAT_SRC"."BIBLIOTHEEK_BEZOCHT" AS "BIBLIOTHEEK_BEZOCHT"
		, "SAT_SRC"."BOEK_GELEZEN" AS "BOEK_GELEZEN"
		, "SAT_SRC"."PARK_BEZOCHT" AS "PARK_BEZOCHT"
		, "SAT_SRC"."RESTAURANT_OF_CAFE_BEZOCHT" AS "RESTAURANT_OF_CAFE_BEZOCHT"
		, "SAT_SRC"."TELEVISIE_GEKEKEN" AS "TELEVISIE_GEKEKEN"
		, "SAT_SRC"."VOORSTELLING_BEZOCHT" AS "VOORSTELLING_BEZOCHT"
		, "SAT_SRC"."SPORT_BEOEFEND" AS "SPORT_BEOEFEND"
		, "SAT_SRC"."THEORETISCH_GESCHOOLDEN" AS "THEORETISCH_GESCHOOLDEN"
		, "SAT_SRC"."AL_SO_GEEN_VERTRAGING" AS "AL_SO_GEEN_VERTRAGING"
		, "SAT_SRC"."SCHOOL_BINNEN_ANTWERPEN" AS "SCHOOL_BINNEN_ANTWERPEN"
		, "SAT_SRC"."PLAATSEN_BUURTPARKINGS" AS "PLAATSEN_BUURTPARKINGS"
		, "SAT_SRC"."PLAATSEN_FIETSENSTALLINGEN" AS "PLAATSEN_FIETSENSTALLINGEN"
		, "SAT_SRC"."PLAATSEN_VELO_STATIONS" AS "PLAATSEN_VELO_STATIONS"
		, "SAT_SRC"."OPP_SPORTTERREINEN" AS "OPP_SPORTTERREINEN"
		, "SAT_SRC"."OPP_GEBRUIKSGROEN_EN_PLEINEN" AS "OPP_GEBRUIKSGROEN_EN_PLEINEN"
		, "SAT_SRC"."OPP_SPEELTERREINEN" AS "OPP_SPEELTERREINEN"
		, "SAT_SRC"."FIETS_PERCENTAGE" AS "FIETS_PERCENTAGE"
	FROM "DEMO_DV_FL"."SAT_PRED_PREDICTIONS" "SAT_SRC"
	INNER JOIN "PRED_STG"."PREDICTIONS" "STG_TEMP_SAT_SRC" ON  "SAT_SRC"."PREDICTIONS_HKEY" = "STG_TEMP_SAT_SRC"."PREDICTIONS_HKEY"
	WHERE  "STG_TEMP_SAT_SRC"."RECORD_TYPE" = 'S' AND "SAT_SRC"."LOAD_END_DATE" = TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')
)
SELECT
	  "TEMP_TABLE_SET"."PREDICTIONS_HKEY" AS "PREDICTIONS_HKEY"
	, "TEMP_TABLE_SET"."LOAD_DATE" AS "LOAD_DATE"
	, "TEMP_TABLE_SET"."LOAD_CYCLE_ID" AS "LOAD_CYCLE_ID"
	, "TEMP_TABLE_SET"."LOAD_END_DATE" AS "LOAD_END_DATE"
	, "TEMP_TABLE_SET"."SOURCE" AS "SOURCE"
	, CASE WHEN "TEMP_TABLE_SET"."SOURCE" = 'STG' AND "TEMP_TABLE_SET"."DELETE_FLAG"  ||
		"TEMP_TABLE_SET"."HASH_DIFF"  = LAG( "TEMP_TABLE_SET"."DELETE_FLAG"  || "TEMP_TABLE_SET"."HASH_DIFF" ,1)
		OVER(PARTITION BY "TEMP_TABLE_SET"."PREDICTIONS_HKEY" ORDER BY "TEMP_TABLE_SET"."LOAD_DATE",
		"TEMP_TABLE_SET"."ORIGIN_ID")THEN 1 ELSE 0 END AS "EQUAL"
	, "TEMP_TABLE_SET"."HASH_DIFF" AS "HASH_DIFF"
	, "TEMP_TABLE_SET"."DELETE_FLAG" AS "DELETE_FLAG"
	, "TEMP_TABLE_SET"."DATUM" AS "DATUM"
	, "TEMP_TABLE_SET"."TIJD" AS "TIJD"
	, "TEMP_TABLE_SET"."POSTCODE" AS "POSTCODE"
	, "TEMP_TABLE_SET"."WERKENDEN" AS "WERKENDEN"
	, "TEMP_TABLE_SET"."BELASTINGSPLICHTIGEN" AS "BELASTINGSPLICHTIGEN"
	, "TEMP_TABLE_SET"."GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON" AS "GEMIDDELD_NETTO_BELASTBAAR_INKOMEN_PER_PERSOON"
	, "TEMP_TABLE_SET"."DICHTHEID" AS "DICHTHEID"
	, "TEMP_TABLE_SET"."BIBLIOTHEEK_BEZOCHT" AS "BIBLIOTHEEK_BEZOCHT"
	, "TEMP_TABLE_SET"."BOEK_GELEZEN" AS "BOEK_GELEZEN"
	, "TEMP_TABLE_SET"."PARK_BEZOCHT" AS "PARK_BEZOCHT"
	, "TEMP_TABLE_SET"."RESTAURANT_OF_CAFE_BEZOCHT" AS "RESTAURANT_OF_CAFE_BEZOCHT"
	, "TEMP_TABLE_SET"."TELEVISIE_GEKEKEN" AS "TELEVISIE_GEKEKEN"
	, "TEMP_TABLE_SET"."VOORSTELLING_BEZOCHT" AS "VOORSTELLING_BEZOCHT"
	, "TEMP_TABLE_SET"."SPORT_BEOEFEND" AS "SPORT_BEOEFEND"
	, "TEMP_TABLE_SET"."THEORETISCH_GESCHOOLDEN" AS "THEORETISCH_GESCHOOLDEN"
	, "TEMP_TABLE_SET"."AL_SO_GEEN_VERTRAGING" AS "AL_SO_GEEN_VERTRAGING"
	, "TEMP_TABLE_SET"."SCHOOL_BINNEN_ANTWERPEN" AS "SCHOOL_BINNEN_ANTWERPEN"
	, "TEMP_TABLE_SET"."PLAATSEN_BUURTPARKINGS" AS "PLAATSEN_BUURTPARKINGS"
	, "TEMP_TABLE_SET"."PLAATSEN_FIETSENSTALLINGEN" AS "PLAATSEN_FIETSENSTALLINGEN"
	, "TEMP_TABLE_SET"."PLAATSEN_VELO_STATIONS" AS "PLAATSEN_VELO_STATIONS"
	, "TEMP_TABLE_SET"."OPP_SPORTTERREINEN" AS "OPP_SPORTTERREINEN"
	, "TEMP_TABLE_SET"."OPP_GEBRUIKSGROEN_EN_PLEINEN" AS "OPP_GEBRUIKSGROEN_EN_PLEINEN"
	, "TEMP_TABLE_SET"."OPP_SPEELTERREINEN" AS "OPP_SPEELTERREINEN"
	, "TEMP_TABLE_SET"."FIETS_PERCENTAGE" AS "FIETS_PERCENTAGE"
FROM "TEMP_TABLE_SET"
;




 
