
-- SAT_ED_TGT

UPDATE "DEMO_DV_FL"."SAT_PRED_PREDICTIONS" "SAT_ED_TGT"
SET 
	 "LOAD_END_DATE" =  "FILTER_LOAD_END_DATE"."LOAD_END_DATE"
FROM 	( 
	SELECT
		  "CALC_LOAD_END_DATE"."PREDICTIONS_HKEY" AS "PREDICTIONS_HKEY"
		, "CALC_LOAD_END_DATE"."LOAD_DATE" AS "LOAD_DATE"
		, "CALC_LOAD_END_DATE"."LOAD_END_DATE" AS "LOAD_END_DATE"
	FROM 	( 
		SELECT
			  "SAT_TEMP_SRC_US"."PREDICTIONS_HKEY" AS "PREDICTIONS_HKEY"
			, "SAT_TEMP_SRC_US"."LOAD_DATE" AS "LOAD_DATE"
			, COALESCE(LEAD("SAT_TEMP_SRC_US"."LOAD_DATE",1)
				OVER(PARTITION BY "SAT_TEMP_SRC_US"."PREDICTIONS_HKEY" ORDER BY "SAT_TEMP_SRC_US"."LOAD_DATE"),
				TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')) AS "LOAD_END_DATE"
		FROM "PRED_STG"."SAT_PRED_PREDICTIONS_TMP" "SAT_TEMP_SRC_US"
		WHERE  "SAT_TEMP_SRC_US"."EQUAL" = 0
)  "CALC_LOAD_END_DATE"
	WHERE  "CALC_LOAD_END_DATE"."LOAD_END_DATE" != TO_TIMESTAMP('31/12/2999 23:59:59' , 'DD/MM/YYYY HH24:MI:SS')
) "FILTER_LOAD_END_DATE"
WHERE "SAT_ED_TGT"."PREDICTIONS_HKEY" =  "FILTER_LOAD_END_DATE"."PREDICTIONS_HKEY"
  AND "SAT_ED_TGT"."LOAD_DATE" =  "FILTER_LOAD_END_DATE"."LOAD_DATE"
;



 